//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EventsServicesSoap", Namespace="http://tempuri.org/")]
public partial class EventsServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CreateProfilOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetProfilOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateOrUpdateEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCurrentEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetEventOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetEventsOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateOrUpdateGroupSignOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreatePricePoolOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateOrUpdatePricePoolOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetPricePoolOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreatePriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateOrUpdatePriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetPriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetPricePoolsOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeletePriceOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeletePricePoolOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeletePricepoolOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetPricesOperationCompleted;
    
    /// <remarks/>
    public EventsServices() {
        this.Url = "http://localhost:9090/EventsServices.asmx";
    }
    
    /// <remarks/>
    public event CreateProfilCompletedEventHandler CreateProfilCompleted;
    
    /// <remarks/>
    public event GetProfilCompletedEventHandler GetProfilCompleted;
    
    /// <remarks/>
    public event CreateOrUpdateEventCompletedEventHandler CreateOrUpdateEventCompleted;
    
    /// <remarks/>
    public event DeleteEventCompletedEventHandler DeleteEventCompleted;
    
    /// <remarks/>
    public event GetCurrentEventCompletedEventHandler GetCurrentEventCompleted;
    
    /// <remarks/>
    public event GetEventCompletedEventHandler GetEventCompleted;
    
    /// <remarks/>
    public event GetEventsCompletedEventHandler GetEventsCompleted;
    
    /// <remarks/>
    public event CreateOrUpdateGroupSignCompletedEventHandler CreateOrUpdateGroupSignCompleted;
    
    /// <remarks/>
    public event CreatePricePoolCompletedEventHandler CreatePricePoolCompleted;
    
    /// <remarks/>
    public event CreateOrUpdatePricePoolCompletedEventHandler CreateOrUpdatePricePoolCompleted;
    
    /// <remarks/>
    public event GetPricePoolCompletedEventHandler GetPricePoolCompleted;
    
    /// <remarks/>
    public event CreatePriceCompletedEventHandler CreatePriceCompleted;
    
    /// <remarks/>
    public event CreateOrUpdatePriceCompletedEventHandler CreateOrUpdatePriceCompleted;
    
    /// <remarks/>
    public event GetPriceCompletedEventHandler GetPriceCompleted;
    
    /// <remarks/>
    public event GetPricePoolsCompletedEventHandler GetPricePoolsCompleted;
    
    /// <remarks/>
    public event DeletePriceCompletedEventHandler DeletePriceCompleted;
    
    /// <remarks/>
    public event DeletePricePoolCompletedEventHandler DeletePricePoolCompleted;
    
    /// <remarks/>
    public event DeletePricepoolCompletedEventHandler DeletePricepoolCompleted;
    
    /// <remarks/>
    public event GetPricesCompletedEventHandler GetPricesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateProfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ProfilS CreateProfil(string name, string tokenId) {
        object[] results = this.Invoke("CreateProfil", new object[] {
                    name,
                    tokenId});
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateProfil(string name, string tokenId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateProfil", new object[] {
                    name,
                    tokenId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ProfilS EndCreateProfil(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public void CreateProfilAsync(string name, string tokenId) {
        this.CreateProfilAsync(name, tokenId, null);
    }
    
    /// <remarks/>
    public void CreateProfilAsync(string name, string tokenId, object userState) {
        if ((this.CreateProfilOperationCompleted == null)) {
            this.CreateProfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProfilOperationCompleted);
        }
        this.InvokeAsync("CreateProfil", new object[] {
                    name,
                    tokenId}, this.CreateProfilOperationCompleted, userState);
    }
    
    private void OnCreateProfilOperationCompleted(object arg) {
        if ((this.CreateProfilCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateProfilCompleted(this, new CreateProfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ProfilS GetProfil(string name, string tokenid) {
        object[] results = this.Invoke("GetProfil", new object[] {
                    name,
                    tokenid});
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProfil(string name, string tokenid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProfil", new object[] {
                    name,
                    tokenid}, callback, asyncState);
    }
    
    /// <remarks/>
    public ProfilS EndGetProfil(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public void GetProfilAsync(string name, string tokenid) {
        this.GetProfilAsync(name, tokenid, null);
    }
    
    /// <remarks/>
    public void GetProfilAsync(string name, string tokenid, object userState) {
        if ((this.GetProfilOperationCompleted == null)) {
            this.GetProfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfilOperationCompleted);
        }
        this.InvokeAsync("GetProfil", new object[] {
                    name,
                    tokenid}, this.GetProfilOperationCompleted, userState);
    }
    
    private void OnGetProfilOperationCompleted(object arg) {
        if ((this.GetProfilCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProfilCompleted(this, new GetProfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int CreateOrUpdateEvent(int id, string name, System.DateTime startDate, System.DateTime endDate, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] image, string description) {
        object[] results = this.Invoke("CreateOrUpdateEvent", new object[] {
                    id,
                    name,
                    startDate,
                    endDate,
                    image,
                    description});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateOrUpdateEvent(int id, string name, System.DateTime startDate, System.DateTime endDate, byte[] image, string description, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateOrUpdateEvent", new object[] {
                    id,
                    name,
                    startDate,
                    endDate,
                    image,
                    description}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndCreateOrUpdateEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void CreateOrUpdateEventAsync(int id, string name, System.DateTime startDate, System.DateTime endDate, byte[] image, string description) {
        this.CreateOrUpdateEventAsync(id, name, startDate, endDate, image, description, null);
    }
    
    /// <remarks/>
    public void CreateOrUpdateEventAsync(int id, string name, System.DateTime startDate, System.DateTime endDate, byte[] image, string description, object userState) {
        if ((this.CreateOrUpdateEventOperationCompleted == null)) {
            this.CreateOrUpdateEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateEventOperationCompleted);
        }
        this.InvokeAsync("CreateOrUpdateEvent", new object[] {
                    id,
                    name,
                    startDate,
                    endDate,
                    image,
                    description}, this.CreateOrUpdateEventOperationCompleted, userState);
    }
    
    private void OnCreateOrUpdateEventOperationCompleted(object arg) {
        if ((this.CreateOrUpdateEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateOrUpdateEventCompleted(this, new CreateOrUpdateEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool DeleteEvent(int id) {
        object[] results = this.Invoke("DeleteEvent", new object[] {
                    id});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteEvent(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteEvent", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeleteEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteEventAsync(int id) {
        this.DeleteEventAsync(id, null);
    }
    
    /// <remarks/>
    public void DeleteEventAsync(int id, object userState) {
        if ((this.DeleteEventOperationCompleted == null)) {
            this.DeleteEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEventOperationCompleted);
        }
        this.InvokeAsync("DeleteEvent", new object[] {
                    id}, this.DeleteEventOperationCompleted, userState);
    }
    
    private void OnDeleteEventOperationCompleted(object arg) {
        if ((this.DeleteEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteEventCompleted(this, new DeleteEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventS GetCurrentEvent(System.DateTime date) {
        object[] results = this.Invoke("GetCurrentEvent", new object[] {
                    date});
        return ((EventS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCurrentEvent(System.DateTime date, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCurrentEvent", new object[] {
                    date}, callback, asyncState);
    }
    
    /// <remarks/>
    public EventS EndGetCurrentEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventS)(results[0]));
    }
    
    /// <remarks/>
    public void GetCurrentEventAsync(System.DateTime date) {
        this.GetCurrentEventAsync(date, null);
    }
    
    /// <remarks/>
    public void GetCurrentEventAsync(System.DateTime date, object userState) {
        if ((this.GetCurrentEventOperationCompleted == null)) {
            this.GetCurrentEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentEventOperationCompleted);
        }
        this.InvokeAsync("GetCurrentEvent", new object[] {
                    date}, this.GetCurrentEventOperationCompleted, userState);
    }
    
    private void OnGetCurrentEventOperationCompleted(object arg) {
        if ((this.GetCurrentEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCurrentEventCompleted(this, new GetCurrentEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventS GetEvent(int id) {
        object[] results = this.Invoke("GetEvent", new object[] {
                    id});
        return ((EventS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetEvent(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetEvent", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public EventS EndGetEvent(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventS)(results[0]));
    }
    
    /// <remarks/>
    public void GetEventAsync(int id) {
        this.GetEventAsync(id, null);
    }
    
    /// <remarks/>
    public void GetEventAsync(int id, object userState) {
        if ((this.GetEventOperationCompleted == null)) {
            this.GetEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventOperationCompleted);
        }
        this.InvokeAsync("GetEvent", new object[] {
                    id}, this.GetEventOperationCompleted, userState);
    }
    
    private void OnGetEventOperationCompleted(object arg) {
        if ((this.GetEventCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetEventCompleted(this, new GetEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEvents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventS[] GetEvents() {
        object[] results = this.Invoke("GetEvents", new object[0]);
        return ((EventS[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetEvents(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetEvents", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public EventS[] EndGetEvents(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventS[])(results[0]));
    }
    
    /// <remarks/>
    public void GetEventsAsync() {
        this.GetEventsAsync(null);
    }
    
    /// <remarks/>
    public void GetEventsAsync(object userState) {
        if ((this.GetEventsOperationCompleted == null)) {
            this.GetEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventsOperationCompleted);
        }
        this.InvokeAsync("GetEvents", new object[0], this.GetEventsOperationCompleted, userState);
    }
    
    private void OnGetEventsOperationCompleted(object arg) {
        if ((this.GetEventsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetEventsCompleted(this, new GetEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdateGroupSign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CreateOrUpdateGroupSign(int id, int eventId, int profilId, int score) {
        object[] results = this.Invoke("CreateOrUpdateGroupSign", new object[] {
                    id,
                    eventId,
                    profilId,
                    score});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateOrUpdateGroupSign(int id, int eventId, int profilId, int score, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateOrUpdateGroupSign", new object[] {
                    id,
                    eventId,
                    profilId,
                    score}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCreateOrUpdateGroupSign(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CreateOrUpdateGroupSignAsync(int id, int eventId, int profilId, int score) {
        this.CreateOrUpdateGroupSignAsync(id, eventId, profilId, score, null);
    }
    
    /// <remarks/>
    public void CreateOrUpdateGroupSignAsync(int id, int eventId, int profilId, int score, object userState) {
        if ((this.CreateOrUpdateGroupSignOperationCompleted == null)) {
            this.CreateOrUpdateGroupSignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdateGroupSignOperationCompleted);
        }
        this.InvokeAsync("CreateOrUpdateGroupSign", new object[] {
                    id,
                    eventId,
                    profilId,
                    score}, this.CreateOrUpdateGroupSignOperationCompleted, userState);
    }
    
    private void OnCreateOrUpdateGroupSignOperationCompleted(object arg) {
        if ((this.CreateOrUpdateGroupSignCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateOrUpdateGroupSignCompleted(this, new CreateOrUpdateGroupSignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreatePricePool", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CreatePricePool(int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent) {
        object[] results = this.Invoke("CreatePricePool", new object[] {
                    priceId,
                    eventId,
                    placeRangeMin,
                    placeRangeMax,
                    placePercent});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreatePricePool(int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreatePricePool", new object[] {
                    priceId,
                    eventId,
                    placeRangeMin,
                    placeRangeMax,
                    placePercent}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCreatePricePool(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CreatePricePoolAsync(int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent) {
        this.CreatePricePoolAsync(priceId, eventId, placeRangeMin, placeRangeMax, placePercent, null);
    }
    
    /// <remarks/>
    public void CreatePricePoolAsync(int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent, object userState) {
        if ((this.CreatePricePoolOperationCompleted == null)) {
            this.CreatePricePoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePricePoolOperationCompleted);
        }
        this.InvokeAsync("CreatePricePool", new object[] {
                    priceId,
                    eventId,
                    placeRangeMin,
                    placeRangeMax,
                    placePercent}, this.CreatePricePoolOperationCompleted, userState);
    }
    
    private void OnCreatePricePoolOperationCompleted(object arg) {
        if ((this.CreatePricePoolCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreatePricePoolCompleted(this, new CreatePricePoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdatePricePool", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CreateOrUpdatePricePool(int id, int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent) {
        object[] results = this.Invoke("CreateOrUpdatePricePool", new object[] {
                    id,
                    priceId,
                    eventId,
                    placeRangeMin,
                    placeRangeMax,
                    placePercent});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateOrUpdatePricePool(int id, int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateOrUpdatePricePool", new object[] {
                    id,
                    priceId,
                    eventId,
                    placeRangeMin,
                    placeRangeMax,
                    placePercent}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCreateOrUpdatePricePool(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CreateOrUpdatePricePoolAsync(int id, int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent) {
        this.CreateOrUpdatePricePoolAsync(id, priceId, eventId, placeRangeMin, placeRangeMax, placePercent, null);
    }
    
    /// <remarks/>
    public void CreateOrUpdatePricePoolAsync(int id, int priceId, int eventId, int placeRangeMin, int placeRangeMax, float placePercent, object userState) {
        if ((this.CreateOrUpdatePricePoolOperationCompleted == null)) {
            this.CreateOrUpdatePricePoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdatePricePoolOperationCompleted);
        }
        this.InvokeAsync("CreateOrUpdatePricePool", new object[] {
                    id,
                    priceId,
                    eventId,
                    placeRangeMin,
                    placeRangeMax,
                    placePercent}, this.CreateOrUpdatePricePoolOperationCompleted, userState);
    }
    
    private void OnCreateOrUpdatePricePoolOperationCompleted(object arg) {
        if ((this.CreateOrUpdatePricePoolCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateOrUpdatePricePoolCompleted(this, new CreateOrUpdatePricePoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPricePool", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public PricePoolS[] GetPricePool(int eventId) {
        object[] results = this.Invoke("GetPricePool", new object[] {
                    eventId});
        return ((PricePoolS[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPricePool(int eventId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetPricePool", new object[] {
                    eventId}, callback, asyncState);
    }
    
    /// <remarks/>
    public PricePoolS[] EndGetPricePool(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PricePoolS[])(results[0]));
    }
    
    /// <remarks/>
    public void GetPricePoolAsync(int eventId) {
        this.GetPricePoolAsync(eventId, null);
    }
    
    /// <remarks/>
    public void GetPricePoolAsync(int eventId, object userState) {
        if ((this.GetPricePoolOperationCompleted == null)) {
            this.GetPricePoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricePoolOperationCompleted);
        }
        this.InvokeAsync("GetPricePool", new object[] {
                    eventId}, this.GetPricePoolOperationCompleted, userState);
    }
    
    private void OnGetPricePoolOperationCompleted(object arg) {
        if ((this.GetPricePoolCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPricePoolCompleted(this, new GetPricePoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreatePrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool CreatePrice(string name, string image, string description, string path) {
        object[] results = this.Invoke("CreatePrice", new object[] {
                    name,
                    image,
                    description,
                    path});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreatePrice(string name, string image, string description, string path, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreatePrice", new object[] {
                    name,
                    image,
                    description,
                    path}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndCreatePrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void CreatePriceAsync(string name, string image, string description, string path) {
        this.CreatePriceAsync(name, image, description, path, null);
    }
    
    /// <remarks/>
    public void CreatePriceAsync(string name, string image, string description, string path, object userState) {
        if ((this.CreatePriceOperationCompleted == null)) {
            this.CreatePriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePriceOperationCompleted);
        }
        this.InvokeAsync("CreatePrice", new object[] {
                    name,
                    image,
                    description,
                    path}, this.CreatePriceOperationCompleted, userState);
    }
    
    private void OnCreatePriceOperationCompleted(object arg) {
        if ((this.CreatePriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreatePriceCompleted(this, new CreatePriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrUpdatePrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int CreateOrUpdatePrice(int id, string name, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] image, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] asset, string description) {
        object[] results = this.Invoke("CreateOrUpdatePrice", new object[] {
                    id,
                    name,
                    image,
                    asset,
                    description});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateOrUpdatePrice(int id, string name, byte[] image, byte[] asset, string description, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateOrUpdatePrice", new object[] {
                    id,
                    name,
                    image,
                    asset,
                    description}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndCreateOrUpdatePrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void CreateOrUpdatePriceAsync(int id, string name, byte[] image, byte[] asset, string description) {
        this.CreateOrUpdatePriceAsync(id, name, image, asset, description, null);
    }
    
    /// <remarks/>
    public void CreateOrUpdatePriceAsync(int id, string name, byte[] image, byte[] asset, string description, object userState) {
        if ((this.CreateOrUpdatePriceOperationCompleted == null)) {
            this.CreateOrUpdatePriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrUpdatePriceOperationCompleted);
        }
        this.InvokeAsync("CreateOrUpdatePrice", new object[] {
                    id,
                    name,
                    image,
                    asset,
                    description}, this.CreateOrUpdatePriceOperationCompleted, userState);
    }
    
    private void OnCreateOrUpdatePriceOperationCompleted(object arg) {
        if ((this.CreateOrUpdatePriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateOrUpdatePriceCompleted(this, new CreateOrUpdatePriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public PriceS GetPrice(int id) {
        object[] results = this.Invoke("GetPrice", new object[] {
                    id});
        return ((PriceS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPrice(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetPrice", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public PriceS EndGetPrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PriceS)(results[0]));
    }
    
    /// <remarks/>
    public void GetPriceAsync(int id) {
        this.GetPriceAsync(id, null);
    }
    
    /// <remarks/>
    public void GetPriceAsync(int id, object userState) {
        if ((this.GetPriceOperationCompleted == null)) {
            this.GetPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceOperationCompleted);
        }
        this.InvokeAsync("GetPrice", new object[] {
                    id}, this.GetPriceOperationCompleted, userState);
    }
    
    private void OnGetPriceOperationCompleted(object arg) {
        if ((this.GetPriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPriceCompleted(this, new GetPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPricePools", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public PricePoolS[] GetPricePools() {
        object[] results = this.Invoke("GetPricePools", new object[0]);
        return ((PricePoolS[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPricePools(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetPricePools", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public PricePoolS[] EndGetPricePools(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PricePoolS[])(results[0]));
    }
    
    /// <remarks/>
    public void GetPricePoolsAsync() {
        this.GetPricePoolsAsync(null);
    }
    
    /// <remarks/>
    public void GetPricePoolsAsync(object userState) {
        if ((this.GetPricePoolsOperationCompleted == null)) {
            this.GetPricePoolsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricePoolsOperationCompleted);
        }
        this.InvokeAsync("GetPricePools", new object[0], this.GetPricePoolsOperationCompleted, userState);
    }
    
    private void OnGetPricePoolsOperationCompleted(object arg) {
        if ((this.GetPricePoolsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPricePoolsCompleted(this, new GetPricePoolsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool DeletePrice(int id) {
        object[] results = this.Invoke("DeletePrice", new object[] {
                    id});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeletePrice(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeletePrice", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeletePrice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeletePriceAsync(int id) {
        this.DeletePriceAsync(id, null);
    }
    
    /// <remarks/>
    public void DeletePriceAsync(int id, object userState) {
        if ((this.DeletePriceOperationCompleted == null)) {
            this.DeletePriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePriceOperationCompleted);
        }
        this.InvokeAsync("DeletePrice", new object[] {
                    id}, this.DeletePriceOperationCompleted, userState);
    }
    
    private void OnDeletePriceOperationCompleted(object arg) {
        if ((this.DeletePriceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeletePriceCompleted(this, new DeletePriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePricePool", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool DeletePricePool(int id) {
        object[] results = this.Invoke("DeletePricePool", new object[] {
                    id});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeletePricePool(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeletePricePool", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeletePricePool(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeletePricePoolAsync(int id) {
        this.DeletePricePoolAsync(id, null);
    }
    
    /// <remarks/>
    public void DeletePricePoolAsync(int id, object userState) {
        if ((this.DeletePricePoolOperationCompleted == null)) {
            this.DeletePricePoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePricePoolOperationCompleted);
        }
        this.InvokeAsync("DeletePricePool", new object[] {
                    id}, this.DeletePricePoolOperationCompleted, userState);
    }
    
    private void OnDeletePricePoolOperationCompleted(object arg) {
        if ((this.DeletePricePoolCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeletePricePoolCompleted(this, new DeletePricePoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePricepool", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool DeletePricepool(int id) {
        object[] results = this.Invoke("DeletePricepool", new object[] {
                    id});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeletePricepool(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeletePricepool", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeletePricepool(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeletePricepoolAsync(int id) {
        this.DeletePricepoolAsync(id, null);
    }
    
    /// <remarks/>
    public void DeletePricepoolAsync(int id, object userState) {
        if ((this.DeletePricepoolOperationCompleted == null)) {
            this.DeletePricepoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePricepoolOperationCompleted);
        }
        this.InvokeAsync("DeletePricepool", new object[] {
                    id}, this.DeletePricepoolOperationCompleted, userState);
    }
    
    private void OnDeletePricepoolOperationCompleted(object arg) {
        if ((this.DeletePricepoolCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeletePricepoolCompleted(this, new DeletePricepoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public PriceS[] GetPrices() {
        object[] results = this.Invoke("GetPrices", new object[0]);
        return ((PriceS[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPrices(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetPrices", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public PriceS[] EndGetPrices(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PriceS[])(results[0]));
    }
    
    /// <remarks/>
    public void GetPricesAsync() {
        this.GetPricesAsync(null);
    }
    
    /// <remarks/>
    public void GetPricesAsync(object userState) {
        if ((this.GetPricesOperationCompleted == null)) {
            this.GetPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricesOperationCompleted);
        }
        this.InvokeAsync("GetPrices", new object[0], this.GetPricesOperationCompleted, userState);
    }
    
    private void OnGetPricesOperationCompleted(object arg) {
        if ((this.GetPricesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetPricesCompleted(this, new GetPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ProfilS {
    
    private int idField;
    
    private string nameField;
    
    private string avatarField;
    
    private int rankField;
    
    private string tokenidField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string avatar {
        get {
            return this.avatarField;
        }
        set {
            this.avatarField = value;
        }
    }
    
    /// <remarks/>
    public int rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    public string tokenid {
        get {
            return this.tokenidField;
        }
        set {
            this.tokenidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class PriceS {
    
    private int idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private byte[] imageField;
    
    private byte[] pathField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class PricePoolS {
    
    private int idField;
    
    private int eventIdField;
    
    private int priceIdField;
    
    private float placePercentField;
    
    private int placeRangeMinField;
    
    private int placeRangeMaxField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int eventId {
        get {
            return this.eventIdField;
        }
        set {
            this.eventIdField = value;
        }
    }
    
    /// <remarks/>
    public int priceId {
        get {
            return this.priceIdField;
        }
        set {
            this.priceIdField = value;
        }
    }
    
    /// <remarks/>
    public float placePercent {
        get {
            return this.placePercentField;
        }
        set {
            this.placePercentField = value;
        }
    }
    
    /// <remarks/>
    public int placeRangeMin {
        get {
            return this.placeRangeMinField;
        }
        set {
            this.placeRangeMinField = value;
        }
    }
    
    /// <remarks/>
    public int placeRangeMax {
        get {
            return this.placeRangeMaxField;
        }
        set {
            this.placeRangeMaxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class EventS {
    
    private int idField;
    
    private string nameField;
    
    private byte[] imageField;
    
    private string descriptionField;
    
    private System.DateTime startDateField;
    
    private System.DateTime endDateField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreateProfilCompletedEventHandler(object sender, CreateProfilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateProfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateProfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ProfilS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ProfilS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetProfilCompletedEventHandler(object sender, GetProfilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ProfilS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ProfilS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreateOrUpdateEventCompletedEventHandler(object sender, CreateOrUpdateEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateOrUpdateEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateOrUpdateEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DeleteEventCompletedEventHandler(object sender, DeleteEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetCurrentEventCompletedEventHandler(object sender, GetCurrentEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCurrentEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCurrentEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetEventCompletedEventHandler(object sender, GetEventCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetEventsCompletedEventHandler(object sender, GetEventsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventS[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventS[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreateOrUpdateGroupSignCompletedEventHandler(object sender, CreateOrUpdateGroupSignCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateOrUpdateGroupSignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateOrUpdateGroupSignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreatePricePoolCompletedEventHandler(object sender, CreatePricePoolCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreatePricePoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreatePricePoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreateOrUpdatePricePoolCompletedEventHandler(object sender, CreateOrUpdatePricePoolCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateOrUpdatePricePoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateOrUpdatePricePoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetPricePoolCompletedEventHandler(object sender, GetPricePoolCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPricePoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetPricePoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PricePoolS[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PricePoolS[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreatePriceCompletedEventHandler(object sender, CreatePriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreatePriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreatePriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void CreateOrUpdatePriceCompletedEventHandler(object sender, CreateOrUpdatePriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateOrUpdatePriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateOrUpdatePriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetPriceCompletedEventHandler(object sender, GetPriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PriceS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PriceS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetPricePoolsCompletedEventHandler(object sender, GetPricePoolsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPricePoolsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetPricePoolsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PricePoolS[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PricePoolS[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DeletePriceCompletedEventHandler(object sender, DeletePriceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeletePriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeletePriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DeletePricePoolCompletedEventHandler(object sender, DeletePricePoolCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeletePricePoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeletePricePoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DeletePricepoolCompletedEventHandler(object sender, DeletePricepoolCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeletePricepoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeletePricepoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetPricesCompletedEventHandler(object sender, GetPricesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PriceS[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PriceS[])(this.results[0]));
        }
    }
}
